import Voice_Tools3 as v

v.Play_Answer('morning', 'speak')
print('morning processed')
# v.Play_Answer('motivate', 'speak')
# print('motivation processed')
# v.Play_Answer('joke', 'speak')
# print('joke processed')
# v.Play_Answer('weather','speak')
# print('weather processed')
# v.Play_Answer('ainews', 'speak')
# print('AI news processed')
# v.Play_Answer('ukrainenews','speak')
# print('Ukraine processed')
# v.Play_Answer('custom', 'speak')
# print('Custom news processed')
# v.Play_Answer('spy', 'speak ')
# print('Market processed')